version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3003:3003"
    depends_on:
      - db
  db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
