version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3003:3003"
    depends_on:
      - db
      - ollama
  db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
  ollama:
    volumes:
      - './ollama:/root/.ollama'
    image: ollama/ollama
    ports:
      - "11434:11434"
    environment:
      - 'OLLAMA_ORIGINS=*'
